name: "Setup Environment"
description: "A composite action to setup environment with security hardening, checkout, Node.js, and package manager"
inputs:
  pnpm:
    description: "Whether to use pnpm (true) or npm (false)"
    required: false
    default: "false"
  install-flags:
    description: "Additional installation flags"
    required: false
    default: ""
  ref:
    description: "The ref to checkout"
    required: false
    default: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.ref }}
  fetch-depth:
    description: "The fetch depth"
    required: false
    default: 1
  node-version:
    description: "Node.js version to setup"
    required: false
    default: "lts/*"
  use-version-file:
    description: "Whether to use .nvmrc file for Node.js version"
    required: false
    default: "false"
  registry-url:
    description: "Optional registry URL for Node.js setup"
    required: false
    default: ""
  token:
    description: "The token to use for checkout"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}

    - name: Setup pnpm
      if: inputs.pnpm == 'true'
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

    - name: Setup Node.js (with version file)
      if: inputs.use-version-file == 'true'
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version-file: ".nvmrc"
        registry-url: ${{ inputs.registry-url }}
        cache: ${{ inputs.pnpm == 'true' && 'pnpm' || 'npm' }}

    - name: Setup Node.js (with specified version)
      if: inputs.use-version-file != 'true'
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: ${{ inputs.registry-url }}
        cache: ${{ inputs.pnpm == 'true' && 'pnpm' || 'npm' }}

    - name: Install dependencies with pnpm
      if: inputs.pnpm == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile ${{ inputs.install-flags }}

    - name: Install dependencies with npm
      if: inputs.pnpm != 'true'
      shell: bash
      run: npm ci ${{ inputs.install-flags }}
