version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - /
      - /actions/*
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github_actions"
      - "auto-merge"
    cooldown:
      default-days: 3
