name: Auto-merge PRs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.repository == 'nodejs/web-team'
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - uses: ./actions/auto-merge-prs
        with:
          merge-method: queue
