name: Auto-merge PRs

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    if: github.repository == 'nodejs/web-team'
    runs-on: ubuntu-latest
    
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: ./actions/auto-merge-prs
        with:
          merge-method: queue
