# TODO(@avivkeller): Once Node.js and HackMD finish the meeting generator,
# use it instead.
name: Create Meeting

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1'  # Every Monday at 03:00 UTC

permissions:
  pull-requests: read
  issues: write

jobs:
  create-meeting:
    runs-on: ubuntu-latest
    steps:
      - name: Check if this is a valid 4-week cycle
        id: check
        run: |
          WEEK=$(date +%U)
          OFFSET=30 # 1 week before we start meetings
          diff=$(( WEEK - OFFSET ))
          mod=$(( (diff % 4 + 4) % 4 ))
          if (( mod != 0 )); then
            echo "Not a 4th-week-aligned Monday. Skipping."
            echo "run=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "run=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout code
        if: steps.check.outputs.run == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Create meeting issue
        if: steps.check.outputs.run == 'true' || github.event_name == 'workflow_dispatch'
        uses: target/create-meeting-issue@b2959d353c7863f7f96f17d42d7618fd57799201
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MEETING_PATH: .github/meeting.ics
          TIMEZONES: Etc/UTC
          AGENDA_LABEL: web-agenda
          ORG_WIDE: true
